
backend:
  name: github
  repo: Quintin720/NeuroConnect-site
  branch: main

media_folder: "images/uploads" # Folder for uploaded images
public_folder: "/images/uploads" # Public URL for uploaded images

publish_mode: editorial_workflow # Enable drafts & publish flow

collections:
  - name: "blog" # Used in filenames
    label: "Blog Posts" # Sidebar name in CMS
    folder: "blog" # Where to save blog posts
    create: true # Allow creation
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename structure
    format: "frontmatter" # Use frontmatter in markdown
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
