backend:
  name: github
  repo: Quintin720/NeuroConnect-site
  branch: main

media_folder: "images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads" # URL path for uploaded images

collections:
  - name: "blog" # Name of the collection
    label: "Blog" # Label in CMS UI
    folder: "blog" # Folder where blog posts are stored
    create: true # Allow users to create new documents
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # File name template
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

