backend:
  name: github
  repo: Quintin720/NeuroConnect-site
  branch: main

media_folder: "images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads" # URL path for uploaded images

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }